### ISSUE TITLE
UV map texture not being used

### ISSUE THREAD

**Issue by Daniel-Bullock** [carl-vbn/minecraft-voxel-loader#10]
Hi! Love the mod you're the goat. I am running into a problem, where I can't make the program use the active UV map as the texture for the Voxelizer. I'm wondering if this is a problem on my end, like if I have to enable something in Blender I'm not aware of so it will work. Thanks!

**Comment by carl-vbn** [comment]
I haven't tested the script with multiple UV maps, but it should be programmed to always use the active UV map. Are you sure you've selected the right one? If there really is a problem, you can either delete all UV maps you don't want or change the script to always use the UV map you need.
