### ISSUE TITLE
Average Texture pack

### ISSUE THREAD

**Issue by wither735** [carl-vbn/minecraft-voxel-loader#11]
Hello its me again so the last few days i try to make minecraft structures in minecraft but when i tryd to put for example a end ship with the normel textures in to minecraft it replaced the Purpel Ender Blocks with some other blocks because the Average color fits more in with the other blocks. So thats why i am asking if you can maby when you have time make the average color tecture pack so i can see wich average color the blocks from the end ship has and then i can replace the texture in blender from normel textures to the average color withe the McPrep addon or i can just replace them by my self. 
![2021-10-21](https://user-images.githubusercontent.com/89296018/138330467-0e3bed80-f540-4d53-96f9-4334ecc3f4f8.png)
![2021-10-21_19 35 12](https://user-images.githubusercontent.com/89296018/138330583-105460b1-0606-4984-9964-7e721f23bc7b.png)

**Comment by carl-vbn** [comment]
Yeah, that is indeed an inconvenience. The solution you came up with seems like the easiest. The average colors of blocks are saved in a text file in the mod JAR file, which is publicly available [here](https://github.com/carl-vbn/minecraft-voxel-loader/blob/main/src/main/resources/average_colors.txt). As you can see the average color of purpur blocks is 169,125,169 (RGB 0-255 values) or #a97da9 in hex.

Hope this helps!

**Comment by wither735** [comment]
Oh this was fast thank you for the help :D

**Comment by wither735** [comment]
Oh and how i can convert the color numbers like 169 125 169 into hex because this numbers are from rgb but only 0-255 but in blender its diffrent
