### ISSUE TITLE
What to do with color_extractor.py?

### ISSUE THREAD

**Issue by The1stGamer** [carl-vbn/minecraft-voxel-loader#15]
Am I meant to put it in blender as a script like the others? When I do it gives me an error. Currently when I voxelize all of them turn white and I have no clue why, I have tried image textures and UV maps but it is always white. It must have something to do with the color_extractor file. I have the assets folder in there but it doesn't work when I import into blender.

**Comment by carl-vbn** [comment]
The color_extractor.py script was used during development but is not needed for regular use. I don't know why you don't have any color. Have you tried applying vertex colors to your model? But image textures should work as well, just don't forget to write the absolute path to your texture in the voxelizer panel

**Comment by The1stGamer** [comment]
I've played around with blender recently trying to find what you mean by "applying vertex colors" but I haven't seen anything. The only thing I can find online is Vertex Painting. Can you let me know what you mean by applying vertex colors?

**Comment by carl-vbn** [comment]
Sorry, I wasn't clear enough. For colors, the script proceeds as follows:
1. It assigns a white color to all vertices 
2. It checks if a texture was supplied. If so, it assigns every vertex a color from the texture according to the object's active UVMap
3. If no texture was supplied, the script checks if vertex colors are present for the object. These are created in the vertex painting mode. If vertex colors are found, they are used.

I was suggesting you try painting your vertices and check if that gives you a color. If so, your texture probably failed to load.

**Comment by The1stGamer** [comment]
![image](https://user-images.githubusercontent.com/56235257/180613462-7279fe2e-d1b8-4c1d-b529-93f0b00eebfd.png)
For some reason I'm getting this error when putting an image texture into my water sim and trying to voxelize?

**Comment by carl-vbn** [comment]
Issue discussion moved to discord. If more help is needed, feel free to contact me again.
If anyone faces a similar issue, in this case, the problem hasn't been identified clearly but seemed to be related to the model.
