### ISSUE TITLE
Output Directory

### ISSUE THREAD

**Issue by melissabauer** [carl-vbn/minecraft-voxel-loader#16]
hi! first off, I really liked your video! thanks so much for helping everyone as well. 

First off, I'm new to blender / animating, so I think this is a fairly simple issue that you've solved before.
I'm currently attempting to save the files and running into the 'output dir does not exist' problem. I've read through your other comments, so I know that the issue is that it needs to be save on the C:/ rather than D:\\, however I can't find where to change this. I've saved the original animation C:\Users\Melisunae\OneDrive\Desktop\blend_voxel\ there, but I don't know where to change the script directory.

You say to not "use Blender's file browser to select a directory" but basically I'm not sure where else to choose it. 
Thank you so much!

**Comment by carl-vbn** [comment]
Hi! You can actually save it to any drive you like (C: or D:), but the important thing is that the path is absolute, so it should start with C: or D:. 
If you want to save it to a folder named "voxel_data" that is on your D: drive, simply type "D:/voxel_data" into the output directory field on the Voxelizer panel. You also have to create that directory yourself.

Hope this helps!

**Comment by carl-vbn** [comment]
Perfect! Let me know if you run into any further issues.

**Comment by melissabauer** [comment]
hi! everything is working great so far, i was just curious if you could explain what to do when there are multiple objects. I noticed on one of your updates that the combining objects script is no longer needed, but I can't seem to figure out how to have it do both of my objects. thank you so much!
