### ISSUE TITLE
multiple objects

### ISSUE THREAD

**Issue by melissabauer** [carl-vbn/minecraft-voxel-loader#17]
Hi! Everything is working great so far, I'm able to get it to work with a single object all the way through, but I was just curious if you could explain what to do when there are multiple objects. I didn't really understand the read me, and I noticed on one of your updates that the combining objects script is no longer needed, but I can't seem to figure out how to have it do both of my objects. Thank you so much!

**Comment by carl-vbn** [comment]
With the latest version of the blender script, you can just select multiple objects and they will all be voxelized together. I hope that makes sense!

**Comment by melissabauer** [comment]
awesome thank you so much! i actually had the camera and light source grabbed, so it was confused, but after i deleted those it worked great. thank you again!
