### ISSUE TITLE
Provide example voxel files

### ISSUE THREAD

**Issue by BitesizedLion** [carl-vbn/minecraft-voxel-loader#18]
Hi, could you possibly provide example voxel animation files for those who would just like to try the mod without firing up blender and using a bunch of scripts?

Understandable if you aren't able to but it would be greatly appreciated.

**Comment by carl-vbn** [comment]
I unfortunately won't have access to the files for a few days, but I'll be happy to provide them after that

**Comment by carl-vbn** [comment]
Sorry for the long wait. Here are some animations I created which you can use. Simply extract the file's contents into your voxelData folder
[Examples.zip](https://github.com/carl-vbn/minecraft-voxel-loader/files/9254707/Examples.zip)
.

**Comment by BitesizedLion** [comment]
> Sorry for the long wait. Here are some animations I created which you can use. Simply extract the file's contents into your voxelData folder [Examples.zip](https://github.com/carl-vbn/minecraft-voxel-loader/files/9254707/Examples.zip) .

No worries, I appreciate it, thank you.
