### ISSUE TITLE
Commands are not working

### ISSUE THREAD

**Issue by YaBoiWaaaaafle** [carl-vbn/minecraft-voxel-loader#19]
Im trying to load the animation into the world, but it doesnt say that the commands are a thing. Did I put the export for the Blender in a wrong spot? Or did I install the mod wrong. Right now in my mods folder I have Fabric API and gradle-wrapper.jar

**Comment by carl-vbn** [comment]
Hello! You don't need "gradle-wrapper.jar". Instead, you need the mod jar file which you can get here: https://github.com/carl-vbn/minecraft-voxel-loader/releases/download/v1.1-mc1.19/vxloader-mc1.19-v1.1.0.jar

**Comment by YaBoiWaaaaafle** [comment]
Thank you! I assumed I downloaded the wrong thing

**Comment by YaBoiWaaaaafle** [comment]
There still seems to be a problem, where Am I supposed to put the Blender Outputs

**Comment by carl-vbn** [comment]
Create a subfolder inside ```.minecraft\VoxelLoader\voxelData\``` and put your .blocks files there. The name of this subfolder is what you'll use in the commands for "dirname".
