### ISSUE TITLE
Misunderstood

### ISSUE THREAD

**Issue by FoxcatgamingZ** [carl-vbn/minecraft-voxel-loader#22]
Hi I recently saw your youtube video on this and thought it was interesting and that I would give it a try, so I made a quick animation and followed all the instructions in the read me stuff and upon loading into the game it registers the bounds for where the object should be however only the top and bottom corners appear and I can't seem to figure out what went wrong. I'm on version 1.19.1 and reading through a couple other posts you said it shouldn't matter if you have multiple objects right?
![73](https://user-images.githubusercontent.com/52290347/181920229-72d32b99-e8b1-4aaa-baae-d879e2ca93cc.png)

**Comment by carl-vbn** [comment]
If your model doesn't have many vertices, try adding a subdivision surface modifier to it. The script only uses vertices to create voxels.

**Comment by FoxcatgamingZ** [comment]
that confuses me because this is my model
![image](https://user-images.githubusercontent.com/52290347/181925908-438048cd-076b-4d58-93b8-b306b7247358.png)


I mostly wanted to try this because of the portion where you did a minecraft steve walking through a plains biome

**Comment by carl-vbn** [comment]
I admit your model looks like it should work. Is it maybe made out of multiple objects and you only selected one?

**Comment by FoxcatgamingZ** [comment]
while yes it is made of multiple objects I did make sure to select all of it when I pressed the voxelize button. I'm questioning if it's because some parts are small enough it can't read them or something like that. does scale have anything to do with how it works?

**Comment by carl-vbn** [comment]
The script will convert the model into voxels according to the 1 m = 1 block scale, but if the bounds seem right, the scale should be good. I really don't know why it isn't working with your specific model. Maybe try it with a simpler model to see if that works?

**Comment by carl-vbn** [comment]
Closed due to inactivity. Feel free to open it again.
