### ISSUE TITLE
voxel colors

### ISSUE THREAD

**Issue by melissabauer** [carl-vbn/minecraft-voxel-loader#24]
hi, i'm having difficulty changing the voxel colors. I have the base color as colors other than white, but during the scripting no other colors show up. then, i've also tried UV mapping, but seem unable to get that to work either. would you be able to help me on discord? my tag is melisunae#5065 and i'd really appreciate it- it feels like i've tried everything.

**Comment by carl-vbn** [comment]
Hello! There are two ways to add colors to your animations:
1. Use vertex painting
2. Use a texture, but in that case you can only use a single texture per model and you have to specify the path to your texture in the voxelizer panel.

If you have more questions, feel free to join my Discord server: https://discord.gg/FJqqvqHaZS

**Comment by melissabauer** [comment]
thank you! i'll move there i appreciate it.
