### ISSUE TITLE
Block Glich

### ISSUE THREAD

**Issue by wither735** [carl-vbn/minecraft-voxel-loader#8]
Hello idk if youre remember me but i am the guy that Submit the first Issue here.

After i tried out youre amazing mod for a few weeks i found a (glich) its not really a glich but when you import a model that has a green texture for example a creeper head then it will start pleacing kelp because its green but then the kelp will also place water its same with other water lockd blocks like the heart of the see. I dont know if you have time to fix but it would be amazing but when not its also ok :D 

https://user-images.githubusercontent.com/89296018/136014960-e637b208-71d5-4ee8-8266-4e1f53992d6f.mp4

**Comment by wither735** [comment]
Oh and here are some Animation that i created not really something special just some random stuff to try out things xD

https://user-images.githubusercontent.com/89296018/136015805-2aec3490-2ede-42fd-9a3f-89f9afcf19ff.mp4


https://user-images.githubusercontent.com/89296018/136015812-ff3e4f2d-9955-45e6-b719-1d801c47af25.mp4


https://user-images.githubusercontent.com/89296018/136015826-1ceb9266-211c-4c42-8487-0f3b5e0ccad9.mp4


https://user-images.githubusercontent.com/89296018/136015838-eaa561a3-d1e3-434b-91fd-86f65704d308.mp4

**Comment by carl-vbn** [comment]
Nice animations, however the glitch you're talking about should be fixed with [the newest version of the mod](https://github.com/carl-vbn/minecraft-voxel-loader/releases/tag/v1.1.0)!

**Comment by wither735** [comment]
Oh really i dont saw that thank you for youre help xD

**Comment by wither735** [comment]
One last Question do i still need to use the sequence_merger.py to use multiple object at ones and do i now need farbric api 1.17.1

**Comment by wither735** [comment]
Oh Closed

**Comment by carl-vbn** [comment]
If you use the latest version of the script you can export multiple objects at once by selecting them all before pressing voxelize. I'm not sure if you need Fabric API 1.17.1, but you will need to update the Fabric Loader to that version.

You can still comment on this issue, I just closed it because the original issue has been resolved.

**Comment by wither735** [comment]
Ah ok thank you :D

**Comment by wither735** [comment]
I tried out the new Version of the script and i have a question when i try to export multiple objects at once how i can select 1 Texture for 1 Object because there is still just 1 slot for the immage texture.

**Comment by carl-vbn** [comment]
Currently, only one texture is supported. You either have to combine all textures into one and adjust the UVs accordingly, or resort to the merger script again.
